### ISSUE TITLE
Detailed ReadMe

### ISSUE THREAD

**Issue by mrdeadlocked** [tylergunn/Snipe-It-Inventory-Checkout#3]
Do you have any screenshots or a demo of what this page looks like?

**Comment by tylergunn** [comment]
I currently do not have any screenshots or a demo page I will work on that in the future.

**Comment by mrdeadlocked** [comment]
Okay. Is it possible to run this without building it in docker?

**Comment by tylergunn** [comment]
You can use Flask but don't use this for production. download the files after those are installed make sure that Python is installed. After that do `pip install -r requirements.txt`. Then do `python server.py`. The commands need to be run in the root directory.

**Comment by mrdeadlocked** [comment]
Awesome. I did get it to work with your directions. the printers chart works, but I am still looking into the Checkout/in and inventory. This isn't production. I am just testing/messing around.

**Comment by tylergunn** [comment]
So, The name is not required the location pulls from the Snipe-It Locations. The asset is the asset name in Snipe-IT. After you enter the required information it will check if the asset is checked in or out. based on that it will check it in/out. This was created for users to be able to check in/out without needing a username and password to snipe it. For the locations, one takes an asset name and adds a note saying found in snipe-it.

**Comment by mrdeadlocked** [comment]
Interesting. Ya those 2 screens do not seem to work with a default setup and seed info.

Inventory Tab
I put in a serialnumber and hit submit. I get 'inventory updated' but I don't see any activity in snipe-it

Checkout/IN
Name Field I put in a Asset name of a devices, Pick a location in dropdown, and then Asset tag. I have only see "Asset Not Found' come up.

**Comment by tylergunn** [comment]
Are you getting a error on the console?

**Comment by mrdeadlocked** [comment]
Inventory Console

http://192.168.1.84/api/v1/hardware/bytag/123
{'status': 'error', 'messages': 'Asset does not exist.', 'payload': None}
No Product Found

I put in Serial Number 123 which matches

![image](https://user-images.githubusercontent.com/461352/236058035-d62ae3bb-b5cf-40b7-8d3b-46012e2a7673.png)

Checkin/out tab Console

http://192.168.1.84/api/v1/hardware/bytag/123
{'status': 'error', 'messages': 'Asset does not exist.', 'payload': None}
No Product Found

I used the same asset as above

**Comment by tylergunn** [comment]
It goes off of the asset tag and not the serial number.

**Comment by mrdeadlocked** [comment]
Ah yep.  It's now giving this error. Are you using a specific status_id?

http://192.168.1.84/api/v1/hardware/bytag/617368595
{'id': 299, 'name': 'blah', 'asset_tag': '617368595', 'serial': '123', 'model': {'id': 1, 'name': 'Macbook Pro 13&quot;'}, 'byod': False, 'model_number': '2221900997009972', 'eol': 36, 'asset_eol_date': {'date': '2025-10-04', 'formatted': '2025-10-04'}, 'status_label': {'id': 1, 'name': 'Ready to Deploy', 'status_type': 'deployable', 'status_meta': 'deployable'}, 'category': {'id': 1, 'name': 'Laptops'}, 'manufacturer': None, 'supplier': {'id': 2, 'name': 'Treutel and Sons'}, 'notes': 'Checked Out', 'order_number': '31274585', 'company': None, 'location': {'id': 3, 'name': 'New Mya'}, 'rtd_location': {'id': 3, 'name': 'New Mya'}, 'image': 'http://192.168.1.84/uploads/models/mbp.jpg', 'qr': None, 'alt_barcode': 'http://192.168.1.84/uploads/barcodes/c128-617368595.png', 'assigned_to': None, 'warranty_months': None, 'warranty_expires': None, 'created_at': {'datetime': '2023-05-03 03:48:18', 'formatted': '2023-05-03 03:48 AM'}, 'updated_at': {'datetime': '2023-05-03 19:52:39', 'formatted': '2023-05-03 07:52 PM'}, 'last_audit_date': None, 'next_audit_date': None, 'deleted_at': None, 'purchase_date': {'date': '2022-10-04', 'formatted': '2022-10-04'}, 'age': '6 months ago', 'last_checkout': None, 'expected_checkin': None, 'purchase_cost': '571.90', 'checkin_counter': 0, 'checkout_counter': 0, 'requests_counter': 0, 'user_can_checkout': True, 'custom_fields': {'RAM': {'field': '_snipeit_ram_3', 'value': '', 'field_format': 'ANY', 'element': 'text'}, 'CPU': {'field': '_snipeit_cpu_4', 'value': '', 'field_format': 'ANY', 'element': 'text'}, 'MAC Address': {'field': '_snipeit_mac_address_5', 'value': '', 'field_format': 'regex:/^([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}$/', 'element': 'text'}}, 'available_actions': {'checkout': True, 'checkin': True, 'clone': True, 'restore': False, 'update': True, 'delete': True}}
Asset Found
{'message': 'The given data was invalid.', 'errors': {'status_id': ['The selected status id is invalid.']}}

**Comment by mrdeadlocked** [comment]
Ah. I got it. I had to update the functions.py to go to a deployable status_id.

**Comment by mrdeadlocked** [comment]
One note, The Inventory 'tab/screen' should be updated to be Asset name not Serial.  I did get this to work after using the Asset Name. That is pretty slick.

![image](https://user-images.githubusercontent.com/461352/236065447-375bf859-f7d6-46e0-bcbe-3d771ff15daa.png)

**Comment by mrdeadlocked** [comment]
Is a main.css file missing from your repo?

<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

Seeing this in console

[03/May/2023 18:44:38] "GET /static/css/main.css HTTP/1.1" 404 -

**Comment by tylergunn** [comment]
main.css is not missing I need to remove that from the code it's not being used. In the future, I will fix the status error so that it grabs the correct status code instead of it being a set number. I also plan on making it so you can use your custom logo and links.
